import React, { createContext, useContext, useState } from 'react';

// Base template — fallback for any missing key in partial translations
const BASE = {
    startQuiz: 'Start Quiz →',
    chooseOne: 'Choose one',
    chooseOneOrMore: 'Choose one or more',
    submitAnswer: 'Submit Answer',
    submitting: 'Submitting...',
    nextQuestion: 'Next Question →',
    finishQuiz: 'Finish Quiz 🎉',
    takeYourTime: 'Take your time. Choose the option that feels most like you.',
    completed: 'Amazing! You Did It! 🎉',
    completedMsg: "You've completed the quiz and discovered something special about yourself!",
    yourPersonality: '🌟 Your Personality Report',
    quizInsights: 'Here are the unique traits revealed across your journey:',
    tryAnotherQuiz: '🔁 Try Another Quiz',
    shareResult: '📤 Share Result',
    loading: 'Loading...',
    tryAgain: 'Try Again',
    goHome: 'Go Home',
    adminLogin: '🔐 Admin',
    adminTitle: '🔐 Admin Dashboard',
    adminPassword: 'Enter admin password',
    adminLogin2: 'Login',
    adminLogout: 'Logout',
    totalQuizzes: 'Total Quizzes',
    totalStarts: 'Total Starts',
    totalCompletions: 'Total Completions',
    completionRate: 'Completion Rate',
    quizPerformance: 'Quiz Performance',
    backToQuizzes: '← Back to Quizzes',
    downloadCSV: '⬇️ Download CSV',
    starts: 'Starts',
    completions: 'Completions',
    avgTime: 'Avg Time',
    topCategories: 'Top Insight Categories',
    wrongPassword: 'Wrong password. Try again.',
    question: 'Question',
    of: 'of',
    seconds: 'seconds',
    failedToStartQuiz: 'Failed to start quiz. Please try again.',
    failedToSubmitAnswer: 'Failed to submit answer. Please try again.',
    copiedToClipboard: 'Copied to clipboard!',
    failedToLoadQuizzes: 'Failed to load quizzes. Please try again.',
    translating: 'Translating...',
    feedbackBadges: [
        '✨ Insight Unlocked', '🔮 Trait Revealed', '🌊 Deep Dive', '🌱 Growth Point',
        '🎪 Personality Peek', '🌸 Self-Discovery', '⚡ Energy Reading', '🌌 Inner World',
    ],
};

const translations = {
    // ── INTERNATIONAL ──────────────────────────────────────────────
    en: {
        ...BASE,
        name: 'English', flag: '🇬🇧', region: 'International',
        tagline: 'Discover Something Amazing About Yourself',
        subtitle: 'In Just 60 Seconds',
        heroTagline: 'Each quiz reveals a different aspect of your personality',
        startQuiz: 'Start Quiz →',
        chooseOne: 'Choose one',
        chooseOneOrMore: 'Choose one or more',
        submitAnswer: 'Submit Answer',
        submitting: 'Submitting...',
        nextQuestion: 'Next Question →',
        finishQuiz: 'Finish Quiz 🎉',
        takeYourTime: 'Take your time. Choose the option that feels most like you.',
        completed: 'Amazing! You Did It! 🎉',
        completedMsg: "You've completed the quiz and discovered something special about yourself!",
        yourPersonality: '🌟 Your Personality Report',
        quizInsights: 'Here are the unique traits revealed across your journey:',
        tryAnotherQuiz: '🔁 Try Another Quiz',
        shareResult: '📤 Share Result',
        loading: 'Loading...',
        tryAgain: 'Try Again',
        goHome: 'Go Home',
        adminLogin: '🔐 Admin',
        adminTitle: '🔐 Admin Dashboard',
        adminPassword: 'Enter admin password',
        adminLogin2: 'Login',
        adminLogout: 'Logout',
        totalQuizzes: 'Total Quizzes',
        totalStarts: 'Total Starts',
        totalCompletions: 'Total Completions',
        completionRate: 'Completion Rate',
        quizPerformance: 'Quiz Performance',
        backToQuizzes: '← Back to Quizzes',
        downloadCSV: '⬇️ Download CSV',
        starts: 'Starts',
        completions: 'Completions',
        avgTime: 'Avg Time',
        topCategories: 'Top Insight Categories',
        wrongPassword: 'Wrong password. Try again.',
        question: 'Question',
        of: 'of',
        seconds: 'seconds',
    },
    hi: {
        name: 'हिंदी',
        flag: '🇮🇳',
        tagline: 'अपने बारे में कुछ अद्भुत खोजें',
        subtitle: 'बस 60 सेकंड में',
        heroTagline: 'हर क्विज़ आपके व्यक्तित्व का एक अलग पहलू उजागर करता है',
        startQuiz: 'क्विज़ शुरू करें →',
        chooseOne: 'एक चुनें',
        chooseOneOrMore: 'एक या अधिक चुनें',
        submitAnswer: 'उत्तर जमा करें',
        submitting: 'जमा हो रहा है...',
        nextQuestion: 'अगला प्रश्न →',
        finishQuiz: 'क्विज़ समाप्त करें 🎉',
        takeYourTime: 'समय लें। वह विकल्प चुनें जो आपको सबसे उपयुक्त लगे।',
        completed: 'शानदार! आपने कर दिखाया! 🎉',
        completedMsg: 'आपने क्विज़ पूरा किया और अपने बारे में कुछ खास जाना!',
        yourPersonality: '🌟 आपकी व्यक्तित्व रिपोर्ट',
        quizInsights: 'आपकी यात्रा में उजागर हुई अनूठी विशेषताएं:',
        tryAnotherQuiz: '🔁 दूसरी क्विज़ आज़माएं',
        shareResult: '📤 परिणाम साझा करें',
        loading: 'लोड हो रहा है...',
        tryAgain: 'पुनः प्रयास करें',
        goHome: 'होम पर जाएं',
        adminLogin: '🔐 एडमिन',
        adminTitle: '🔐 एडमिन डैशबोर्ड',
        adminPassword: 'एडमिन पासवर्ड दर्ज करें',
        adminLogin2: 'लॉगिन',
        adminLogout: 'लॉगआउट',
        totalQuizzes: 'कुल क्विज़',
        totalStarts: 'कुल शुरुआत',
        totalCompletions: 'कुल समापन',
        completionRate: 'समापन दर',
        quizPerformance: 'क्विज़ प्रदर्शन',
        backToQuizzes: '← क्विज़ पर वापस',
        downloadCSV: '⬇️ CSV डाउनलोड करें',
        starts: 'शुरुआत',
        completions: 'समापन',
        avgTime: 'औसत समय',
        topCategories: 'शीर्ष अंतर्दृष्टि श्रेणियां',
        wrongPassword: 'गलत पासवर्ड। पुनः प्रयास करें।',
        question: 'प्रश्न',
        of: 'में से',
        seconds: 'सेकंड',
        failedToStartQuiz: 'क्विज़ शुरू करने में समस्या। पुनः प्रयास करें।',
        failedToSubmitAnswer: 'उत्तर जमा करने में समस्या। पुनः प्रयास करें।',
        copiedToClipboard: 'कॉपी हो गया!',
        failedToLoadQuizzes: 'क्विज़ लोड करने में समस्या। पुनः प्रयास करें।',
        translating: 'अनुवाद हो रहा है...',
        feedbackBadges: [
            '✨ अंतर्दृष्टि मिली', '🔮 विशेषता प्रकट', '🌊 गहरी पड़ताल', '🌱 विकास बिंदु',
            '🎪 व्यक्तित्व झलक', '🌸 आत्म-खोज', '⚡ ऊर्जा पठन', '🌌 अंतर्मन',
        ],
    },
    te: {
        name: 'తెలుగు',
        flag: '🏛️',
        tagline: 'మీ గురించి అద్భుతమైనది కనుగొనండి',
        subtitle: 'కేవలం 60 సెకన్లలో',
        heroTagline: 'ప్రతి క్విజ్ మీ వ్యక్తిత్వంలో ఒక అంశాన్ని వెల్లడిస్తుంది',
        startQuiz: 'క్విజ్ ప్రారంభించు →',
        chooseOne: 'ఒకటి ఎంచుకోండి',
        chooseOneOrMore: 'ఒకటి లేదా అంతకంటే ఎక్కువ ఎంచుకోండి',
        submitAnswer: 'సమాధానం సమర్పించు',
        submitting: 'సమర్పిస్తోంది...',
        nextQuestion: 'తదుపరి ప్రశ్న →',
        finishQuiz: 'క్విజ్ ముగించు 🎉',
        takeYourTime: 'సమయం తీసుకోండి. మీకు నచ్చిన ఎంపికను ఎంచుకోండి.',
        completed: 'అద్భుతం! మీరు చేశారు! 🎉',
        completedMsg: 'మీరు క్విజ్ పూర్తి చేసి మీ గురించి ప్రత్యేకమైనది తెలుసుకున్నారు!',
        yourPersonality: '🌟 మీ వ్యక్తిత్వ నివేదిక',
        quizInsights: 'మీ ప్రయాణంలో వెల్లడైన అనన్య లక్షణాలు:',
        tryAnotherQuiz: '🔁 మరొక క్విజ్ ప్రయత్నించండి',
        shareResult: '📤 ఫలితం పంచుకోండి',
        loading: 'లోడ్ అవుతోంది...',
        tryAgain: 'మళ్ళీ ప్రయత్నించండి',
        goHome: 'హోమ్‌కు వెళ్ళు',
        adminLogin: '🔐 అడ్మిన్',
        adminTitle: '🔐 అడ్మిన్ డాష్‌బోర్డ్',
        adminPassword: 'అడ్మిన్ పాస్‌వర్డ్ నమోదు చేయండి',
        adminLogin2: 'లాగిన్',
        adminLogout: 'లాగ్అవుట్',
        totalQuizzes: 'మొత్తం క్విజ్‌లు',
        totalStarts: 'మొత్తం ప్రారంభాలు',
        totalCompletions: 'మొత్తం పూర్తవడాలు',
        completionRate: 'పూర్తి రేటు',
        quizPerformance: 'క్విజ్ పనితీరు',
        backToQuizzes: '← క్విజ్‌లకు వెనుకకు',
        downloadCSV: '⬇️ CSV డౌన్‌లోడ్',
        starts: 'ప్రారంభాలు',
        completions: 'పూర్తవడాలు',
        avgTime: 'సగటు సమయం',
        topCategories: 'అగ్ర అంతర్దృష్టి వర్గాలు',
        wrongPassword: 'తప్పు పాస్‌వర్డ్. మళ్ళీ ప్రయత్నించండి.',
        question: 'ప్రశ్న',
        of: 'లో',
        seconds: 'సెకన్లు',
        failedToStartQuiz: 'క్విజ్ ప్రారంభించడం విఫలమైంది. మళ్ళీ ప్రయత్నించండి.',
        failedToSubmitAnswer: 'సమాధానం సమర్పించడం విఫలమైంది. మళ్ళీ ప్రయత్నించండి.',
        copiedToClipboard: 'క్లిప్‌బోర్డ్‌కు కాపీ అయింది!',
        failedToLoadQuizzes: 'క్విజ్‌లు లోడ్ వ్యర్థమైంది. మళ్ళీ ప్రయత్నించండి.',
        translating: 'అనువదించబడుతోంది...',
        feedbackBadges: [
            '✨ అంతర్దృష్టి వెల్లడి', '🔮 లక్షణం బహిర్గతం', '🌊 లోతైన విశ్లేషణ', '🌱 వృద్ధి బిందువు',
            '🎪 వ్యక్తిత్వ సంచలనం', '🌸 ఆత్మ-అన్వేషణ', '⚡ శక్తి పఠనం', '🌌 అంతరంగం',
        ],
    },
    ta: {
        name: 'தமிழ்',
        flag: '🌺',
        tagline: 'உங்களைப் பற்றி அற்புதமானதை கண்டுபிடியுங்கள்',
        subtitle: 'வெறும் 60 வினாடிகளில்',
        heroTagline: 'ஒவ்வொரு வினாடியும் உங்கள் ஆளுமையின் ஒரு அம்சத்தை வெளிப்படுத்துகிறது',
        startQuiz: 'வினாடி வினா தொடங்கு →',
        chooseOne: 'ஒன்று தேர்ந்தெடுக்கவும்',
        chooseOneOrMore: 'ஒன்று அல்லது அதிகம் தேர்ந்தெடுக்கவும்',
        submitAnswer: 'பதில் சமர்பி',
        submitting: 'சமர்பிக்கிறது...',
        nextQuestion: 'அடுத்த கேள்வி →',
        finishQuiz: 'முடி 🎉',
        takeYourTime: 'நேரம் எடுக்கவும். உங்களுக்கு பொருந்தும் விருப்பத்தை தேர்ந்தெடுக்கவும்.',
        completed: 'அற்புதம்! நீங்கள் செய்தீர்கள்! 🎉',
        completedMsg: 'நீங்கள் வினாடி வினாவை முடித்து உங்களைப் பற்றி சிறப்பானதை கண்டறிந்தீர்கள்!',
        yourPersonality: '🌟 உங்கள் ஆளுமை அறிக்கை',
        quizInsights: 'உங்கள் பயணத்தில் வெளிப்பட்ட தனித்துவமான பண்புகள்:',
        tryAnotherQuiz: '🔁 மற்றொரு வினாடி வினா முயற்சிக்கவும்',
        shareResult: '📤 முடிவை பகிரவும்',
        loading: 'ஏற்றுகிறது...',
        tryAgain: 'மீண்டும் முயற்சி',
        goHome: 'முகப்புக்கு செல்',
        adminLogin: '🔐 நிர்வாகி',
        adminTitle: '🔐 நிர்வாகி டாஷ்போர்டு',
        adminPassword: 'நிர்வாக கடவுச்சொல் உள்ளிடுக',
        adminLogin2: 'உள்நுழை',
        adminLogout: 'வெளியேறு',
        totalQuizzes: 'மொத்த வினாடி வினாக்கள்',
        totalStarts: 'மொத்த தொடக்கங்கள்',
        totalCompletions: 'மொத்த முடிவுகள்',
        completionRate: 'முடிவு விகிதம்',
        quizPerformance: 'வினாடி வினா செயல்திறன்',
        backToQuizzes: '← வினாடி வினாக்களுக்கு திரும்பு',
        downloadCSV: '⬇️ CSV பதிவிறக்கம்',
        starts: 'தொடக்கங்கள்',
        completions: 'முடிவுகள்',
        avgTime: 'சராசரி நேரம்',
        topCategories: 'சிறந்த நுண்ணறிவு வகைகள்',
        wrongPassword: 'தவறான கடவுச்சொல். மீண்டும் முயற்சிக்கவும்.',
        question: 'கேள்வி',
        of: 'இல்',
        seconds: 'வினாடிகள்',
        failedToStartQuiz: 'வினாடி வினா தொடங்க முடியவில்லை. மீண்டும் முயலவும்.',
        failedToSubmitAnswer: 'பதில் சமர்ப்பிக்க முடியவில்லை. மீண்டும் முயலவும்.',
        copiedToClipboard: 'கிளிப்போர்டுக்கு நகலெடுக்கப்பட்டது!',
        failedToLoadQuizzes: 'வினாடி வினாக்களை ஏற்ற முடியவில்லை. மீண்டும் முயலவும்.',
        translating: 'மொழிபெயர்க்கிறது...',
        feedbackBadges: [
            '✨ நுண்ணறிவு திறக்கப்பட்டது', '🔮 குணம் வெளிப்பட்டது', '🌊 ஆழமான பகுப்பாய்வு', '🌱 வளர்ச்சி புள்ளி',
            '🎪 ஆளுமை பார்வை', '🌸 சுய-கண்டுபிடிப்பு', '⚡ ஆற்றல் வாசிப்பு', '🌌 உள்ளுணர்வு',
        ],
    },
    kn: {
        name: 'ಕನ್ನಡ',
        flag: '🌻',
        tagline: 'ನಿಮ್ಮ ಬಗ್ಗೆ ಅದ್ಭುತವಾದದ್ದನ್ನು ಕಂಡುಹಿಡಿಯಿರಿ',
        subtitle: 'ಕೇವಲ 60 ಸೆಕೆಂಡ್‌ಗಳಲ್ಲಿ',
        heroTagline: 'ಪ್ರತಿ ಕ್ವಿಜ್ ನಿಮ್ಮ ವ್ಯಕ್ತಿತ್ವದ ಒಂದು ಅಂಶವನ್ನು ಬಹಿರಂಗಪಡಿಸುತ್ತದೆ',
        startQuiz: 'ಕ್ವಿಜ್ ಪ್ರಾರಂಭಿಸಿ →',
        chooseOne: 'ಒಂದನ್ನು ಆರಿಸಿ',
        chooseOneOrMore: 'ಒಂದು ಅಥವಾ ಹೆಚ್ಚು ಆರಿಸಿ',
        submitAnswer: 'ಉತ್ತರ ಸಲ್ಲಿಸಿ',
        submitting: 'ಸಲ್ಲಿಸಲಾಗುತ್ತಿದೆ...',
        nextQuestion: 'ಮುಂದಿನ ಪ್ರಶ್ನೆ →',
        finishQuiz: 'ಕ್ವಿಜ್ ಮುಗಿಸಿ 🎉',
        takeYourTime: 'ಸಮಯ ತೆಗೆದುಕೊಳ್ಳಿ. ನಿಮಗೆ ಹೊಂದುವ ಆಯ್ಕೆಯನ್ನು ಆರಿಸಿ.',
        completed: 'ಅದ್ಭುತ! ನೀವು ಮಾಡಿದಿರಿ! 🎉',
        completedMsg: 'ನೀವು ಕ್ವಿಜ್ ಪೂರ್ಣಗೊಳಿಸಿ ನಿಮ್ಮ ಬಗ್ಗೆ ವಿಶೇಷವಾದದ್ದನ್ನು ಕಂಡುಹಿಡಿದಿದ್ದೀರಿ!',
        yourPersonality: '🌟 ನಿಮ್ಮ ವ್ಯಕ್ತಿತ್ವ ವರದಿ',
        quizInsights: 'ನಿಮ್ಮ ಪ್ರಯಾಣದಲ್ಲಿ ಬಹಿರಂಗಪಟ್ಟ ಅನನ್ಯ ಗುಣಲಕ್ಷಣಗಳು:',
        tryAnotherQuiz: '🔁 ಇನ್ನೊಂದು ಕ್ವಿಜ್ ಪ್ರಯತ್ನಿಸಿ',
        shareResult: '📤 ಫಲಿತಾಂಶ ಹಂಚಿಕೊಳ್ಳಿ',
        loading: 'ಲೋಡ್ ಆಗುತ್ತಿದೆ...',
        tryAgain: 'ಮತ್ತೆ ಪ್ರಯತ್ನಿಸಿ',
        goHome: 'ಮನೆಗೆ ಹೋಗಿ',
        adminLogin: '🔐 ಅಡ್ಮಿನ್',
        adminTitle: '🔐 ಅಡ್ಮಿನ್ ಡ್ಯಾಶ್‌ಬೋರ್ಡ್',
        adminPassword: 'ಅಡ್ಮಿನ್ ಪಾಸ್‌ವರ್ಡ್ ನಮೂದಿಸಿ',
        adminLogin2: 'ಲಾಗಿನ್',
        adminLogout: 'ಲಾಗ್ಔಟ್',
        totalQuizzes: 'ಒಟ್ಟು ಕ್ವಿಜ್‌ಗಳು',
        totalStarts: 'ಒಟ್ಟು ಪ್ರಾರಂಭಗಳು',
        totalCompletions: 'ಒಟ್ಟು ಪೂರ್ಣಗೊಳಿಸುವಿಕೆಗಳು',
        completionRate: 'ಪೂರ್ಣಗೊಳಿಸುವ ದರ',
        quizPerformance: 'ಕ್ವಿಜ್ ಕಾರ್ಯಕ್ಷಮತೆ',
        backToQuizzes: '← ಕ್ವಿಜ್‌ಗಳಿಗೆ ಹಿಂತಿರುಗಿ',
        downloadCSV: '⬇️ CSV ಡೌನ್‌ಲೋಡ್',
        starts: 'ಪ್ರಾರಂಭಗಳು',
        completions: 'ಪೂರ್ಣಗೊಳಿಸುವಿಕೆಗಳು',
        avgTime: 'ಸರಾಸರಿ ಸಮಯ',
        topCategories: 'ಉನ್ನತ ಒಳನೋಟ ವರ್ಗಗಳು',
        wrongPassword: 'ತಪ್ಪಾದ ಪಾಸ್‌ವರ್ಡ್. ಮತ್ತೆ ಪ್ರಯತ್ನಿಸಿ.',
        question: 'ಪ್ರಶ್ನೆ', of: 'ರಲ್ಲಿ', seconds: 'ಸೆಕೆಂಡ್‌ಗಳು',
        failedToStartQuiz: 'ಕ್ವಿಜ್ ಪ್ರಾರಂಭಿಸಲು ವಿಫಲವಾಗಿದೆ. ಮತ್ತೆ ಪ್ರಯತ್ನಿಸಿ.',
        failedToSubmitAnswer: 'ಉತ್ತರ ಸಲ್ಲಿಸುವಲ್ಲಿ ವಿಫಲವಾಗಿದೆ. ಮತ್ತೆ ಪ್ರಯತ್ನಿಸಿ.',
        copiedToClipboard: 'ಕ್ಲಿಪ್‌ಬೋರ್ಡ್‌ಗೆ ನಕಲಿಸಲಾಗಿದೆ!',
        failedToLoadQuizzes: 'ಕ್ವಿಜ್‌ಗಳು ಲೋಡ್ ವಿಫಲವಾಗಿದೆ. ಮತ್ತೆ ಪ್ರಯತ್ನಿಸಿ.',
        translating: 'ಅನುವಾದಿಸಲಾಗುತ್ತಿದೆ...',
        feedbackBadges: [
            '✨ ಒಳನೋಟ ಅನ್ಲಾಕ್', '🔮 ಗುಣ ಬಹಿರಂಗ', '🌊 ಆಳ ವಿಶ್ಲೇಷಣೆ', '🌱 ಬೆಳವಣಿಗೆ ಬಿಂದು',
            '🎪 ವ್ಯಕ್ತಿತ್ವ ಝಲಕ', '🌸 ಆತ್ಮ-ಆವಿಷ್ಕಾರ', '⚡ ಶಕ್ತಿ ಓದು', '🌌 ಅಂತರ್ಮನ',
        ],
    },

    // ── MORE INTERNATIONAL ─────────────────────────────────────────
    es: {
        ...BASE, name: 'Español', flag: '🇪🇸', region: 'International',
        tagline: 'Descubre algo increíble sobre ti', subtitle: 'En solo 60 segundos',
        heroTagline: 'Cada cuestionario revela un aspecto diferente de tu personalidad',
        startQuiz: 'Iniciar →', chooseOne: 'Elige una', chooseOneOrMore: 'Elige una o más',
        submitAnswer: 'Enviar', submitting: 'Enviando...', nextQuestion: 'Siguiente →',
        finishQuiz: 'Finalizar 🎉', takeYourTime: 'Tómate tu tiempo. Elige lo que mejor te represente.',
        completed: '¡Increíble! ¡Lo lograste! 🎉', yourPersonality: '🌟 Tu Perfil de Personalidad',
        tryAnotherQuiz: '🔁 Probar otro', shareResult: '📤 Compartir',
        tryAgain: 'Reintentar', wrongPassword: 'Contraseña incorrecta.',
        question: 'Pregunta', of: 'de', seconds: 'segundos',
        takeYourTime: 'Tómate tu tiempo. Elige la opción que mejor te represente.',
        completedMsg: 'Completaste el test y descubriste algo especial sobre ti.',
        quizInsights: 'Rasgos únicos revelados en tu viaje:',
        goHome: 'Ir al inicio', loading: 'Cargando...',
    },
    fr: {
        ...BASE, name: 'Français', flag: '🇫🇷', region: 'International',
        tagline: 'Découvrez quelque chose d\'incroyable sur vous', subtitle: 'En 60 secondes',
        heroTagline: 'Chaque quiz révèle un aspect différent de votre personnalité',
        startQuiz: 'Commencer →', chooseOne: 'Choisissez-en un', chooseOneOrMore: 'Choisissez-en un ou plusieurs',
        submitAnswer: 'Soumettre', submitting: 'Envoi...', nextQuestion: 'Suivant →',
        finishQuiz: 'Terminer 🎉', completed: 'Incroyable! Vous l\'avez fait! 🎉',
        yourPersonality: '🌟 Votre rapport de personnalité',
        tryAnotherQuiz: '🔁 Essayer un autre', shareResult: '📤 Partager',
        tryAgain: 'Réessayer', question: 'Question', of: 'sur', seconds: 'secondes',
        takeYourTime: 'Prenez votre temps. Choisissez l\'option qui vous ressemble le plus.',
        completedMsg: 'Vous avez terminé le quiz et découvert quelque chose de spécial sur vous.',
        quizInsights: 'Traits uniques révélés au cours de votre parcours :',
        goHome: 'Accueil', loading: 'Chargement...',
    },
    ar: {
        ...BASE, name: 'العربية', flag: '🇸🇦', region: 'International',
        tagline: 'اكتشف شيئاً مذهلاً عن نفسك', subtitle: 'في 60 ثانية فقط',
        heroTagline: 'كل اختبار يكشف جانباً مختلفاً من شخصيتك',
        startQuiz: 'ابدأ →', chooseOne: 'اختر واحداً', chooseOneOrMore: 'اختر واحداً أو أكثر',
        submitAnswer: 'إرسال', submitting: 'جارٍ الإرسال...', nextQuestion: 'التالي →',
        finishQuiz: 'إنهاء 🎉', completed: 'رائع! لقد فعلتها! 🎉',
        yourPersonality: '🌟 تقرير شخصيتك', tryAnotherQuiz: '🔁 جرّب آخر',
        shareResult: '📤 شارك', tryAgain: 'حاول مجدداً',
        wrongPassword: 'كلمة مرور خاطئة.', question: 'سؤال', of: 'من', seconds: 'ثوانٍ',
    },
    zh: {
        ...BASE, name: '中文', flag: '🇨🇳', region: 'International',
        tagline: '发现关于自己的惊人之处', subtitle: '仅需60秒',
        heroTagline: '每个测验揭示您个性的不同方面',
        startQuiz: '开始 →', chooseOne: '选择一项', chooseOneOrMore: '选择一项或多项',
        submitAnswer: '提交', submitting: '提交中...', nextQuestion: '下一题 →',
        finishQuiz: '完成 🎉', completed: '太棒了！你做到了！🎉',
        yourPersonality: '🌟 你的个性报告', tryAnotherQuiz: '🔁 尝试其他',
        shareResult: '📤 分享', tryAgain: '重试', question: '问题', of: '共', seconds: '秒',
    },
    pt: {
        ...BASE, name: 'Português', flag: '🇧🇷', region: 'International',
        tagline: 'Descubra algo incrível sobre você', subtitle: 'Em apenas 60 segundos',
        heroTagline: 'Cada quiz revela um aspecto diferente da sua personalidade',
        startQuiz: 'Iniciar →', chooseOne: 'Escolha um', chooseOneOrMore: 'Escolha um ou mais',
        submitAnswer: 'Enviar', submitting: 'Enviando...', nextQuestion: 'Próxima →',
        finishQuiz: 'Finalizar 🎉', completed: 'Incrível! Você conseguiu! 🎉',
        yourPersonality: '🌟 Seu Relatório de Personalidade',
        tryAnotherQuiz: '🔁 Tentar outro', shareResult: '📤 Compartilhar',
        question: 'Pergunta', of: 'de', seconds: 'segundos',
        takeYourTime: 'Tome seu tempo. Escolha a opção que mais representa você.',
        completedMsg: 'Você completou o quiz e descobriu algo especial sobre si mesmo.',
        quizInsights: 'Traços únicos revelados na sua jornada:',
        goHome: 'Início', loading: 'Carregando...',
    },
    de: {
        ...BASE, name: 'Deutsch', flag: '🇩🇪', region: 'International',
        tagline: 'Entdecke etwas Erstaunliches über dich', subtitle: 'In nur 60 Sekunden',
        heroTagline: 'Jedes Quiz enthüllt einen anderen Aspekt deiner Persönlichkeit',
        startQuiz: 'Starten →', chooseOne: 'Wähle eine', chooseOneOrMore: 'Wähle eine oder mehrere',
        submitAnswer: 'Einreichen', submitting: 'Wird eingereicht...', nextQuestion: 'Nächste →',
        finishQuiz: 'Beenden 🎉', completed: 'Fantastisch! Du hast es geschafft! 🎉',
        yourPersonality: '🌟 Dein Persönlichkeitsbericht',
        tryAnotherQuiz: '🔁 Weiteres probieren', shareResult: '📤 Teilen',
        question: 'Frage', of: 'von', seconds: 'Sekunden',
        takeYourTime: 'Nimm dir Zeit. Wähle die Option, die am besten zu dir passt.',
        completedMsg: 'Du hast das Quiz abgeschlossen und etwas Besonderes über dich entdeckt.',
        quizInsights: 'Einzigartige Eigenschaften, die auf deiner Reise enthüllt wurden:',
        goHome: 'Startseite', loading: 'Lädt...',
    },
    ja: {
        ...BASE, name: '日本語', flag: '🇯🇵', region: 'International',
        tagline: '自分について驚くべきことを発見しよう', subtitle: 'たった60秒で',
        heroTagline: '各クイズはあなたの個性の異なる側面を明らかにします',
        startQuiz: '始める →', chooseOne: '1つ選んでください', chooseOneOrMore: '1つ以上選んでください',
        submitAnswer: '回答を送信', submitting: '送信中...', nextQuestion: '次の質問 →',
        finishQuiz: '終了 🎉', completed: '素晴らしい！やり遂げました！🎉',
        yourPersonality: '🌟 あなたの個性レポート',
        tryAnotherQuiz: '🔁 別のクイズを試す', shareResult: '📤 シェア',
        question: '質問', of: '/', seconds: '秒',
        takeYourTime: '時間をかけて。あなたに最も合う選択肢を選んでください。',
        completedMsg: 'クイズを完了し、自分自身について特別なことを発見しました。',
        quizInsights: 'あなたの旅で明らかになった独自の特徴：',
        goHome: 'ホームへ', loading: '読み込み中...',
    },
    ko: {
        ...BASE, name: '한국어', flag: '🇰🇷', region: 'International',
        tagline: '자신에 대한 놀라운 것을 발견하세요', subtitle: '단 60초 만에',
        heroTagline: '각 퀴즈는 당신의 성격의 다른 면을 드러냅니다',
        startQuiz: '시작 →', chooseOne: '하나 선택', chooseOneOrMore: '하나 이상 선택',
        submitAnswer: '답변 제출', submitting: '제출 중...', nextQuestion: '다음 →',
        finishQuiz: '완료 🎉', completed: '훌륭해요! 해냈어요! 🎉',
        yourPersonality: '🌟 나의 성격 보고서',
        tryAnotherQuiz: '🔁 다른 퀴즈', shareResult: '📤 공유',
        question: '질문', of: '/', seconds: '초',
        takeYourTime: '천천히 하세요. 당신과 가장 잘 맞는 옵션을 선택하세요.',
        completedMsg: '퀴즈를 완료하고 자신에 대한 특별한 것을 발견했습니다.',
        quizInsights: '여정에서 드러난 독특한 특성:',
        goHome: '홈으로', loading: '로딩 중...',
    },
    ru: {
        ...BASE, name: 'Русский', flag: '🇷🇺', region: 'International',
        tagline: 'Откройте что-то удивительное в себе', subtitle: 'Всего за 60 секунд',
        heroTagline: 'Каждая викторина раскрывает новый аспект вашей личности',
        startQuiz: 'Начать →', chooseOne: 'Выберите один', chooseOneOrMore: 'Выберите один или несколько',
        submitAnswer: 'Отправить', submitting: 'Отправка...', nextQuestion: 'Следующий →',
        finishQuiz: 'Завершить 🎉', completed: 'Потрясающе! Вы справились! 🎉',
        yourPersonality: '🌟 Ваш отчёт о личности',
        tryAnotherQuiz: '🔁 Другая викторина', shareResult: '📤 Поделиться',
        question: 'Вопрос', of: 'из', seconds: 'сек',
        takeYourTime: 'Не торопитесь. Выберите ответ, который вам ближе всего.',
        completedMsg: 'Вы прошли викторину и открыли что-то особенное о себе.',
        quizInsights: 'Уникальные черты, открытые в вашем путешествии:',
        goHome: 'На главную', loading: 'Загрузка...',
    },
    id: {
        ...BASE, name: 'Indonesia', flag: '🇮🇩', region: 'International',
        tagline: 'Temukan hal menakjubkan tentang dirimu', subtitle: 'Hanya dalam 60 detik',
        heroTagline: 'Setiap kuis mengungkap sisi berbeda dari kepribadianmu',
        startQuiz: 'Mulai →', chooseOne: 'Pilih satu', chooseOneOrMore: 'Pilih satu atau lebih',
        submitAnswer: 'Kirim', submitting: 'Mengirim...', nextQuestion: 'Berikutnya →',
        finishQuiz: 'Selesai 🎉', completed: 'Luar biasa! Kamu berhasil! 🎉',
        yourPersonality: '🌟 Laporan Kepribadianmu',
        tryAnotherQuiz: '🔁 Coba Kuis Lain', shareResult: '📤 Bagikan',
        question: 'Pertanyaan', of: 'dari', seconds: 'detik',
        takeYourTime: 'Ambil waktumu. Pilih opsi yang paling mewakilimu.',
        completedMsg: 'Kamu menyelesaikan kuis dan menemukan sesuatu yang istimewa tentang dirimu.',
        quizInsights: 'Sifat unik yang terungkap dalam perjalananmu:',
        goHome: 'Beranda', loading: 'Memuat...',
    },
    tr: {
        ...BASE, name: 'Türkçe', flag: '🇹🇷', region: 'International',
        tagline: 'Kendin hakkında şaşırtıcı şeyler keşfet', subtitle: 'Sadece 60 saniyede',
        heroTagline: 'Her test kişiliğinin farklı bir yönünü ortaya çıkarır',
        startQuiz: 'Başlat →', chooseOne: 'Bir seçenek seç', chooseOneOrMore: 'Bir veya daha fazla seç',
        submitAnswer: 'Gönder', submitting: 'Gönderiliyor...', nextQuestion: 'Sonraki →',
        finishQuiz: 'Bitir 🎉', completed: 'Harika! Başardın! 🎉',
        yourPersonality: '🌟 Kişilik Raporun',
        tryAnotherQuiz: '🔁 Başka Test Dene', shareResult: '📤 Paylaş',
        question: 'Soru', of: '/', seconds: 'saniye',
        takeYourTime: 'Zamanını al. Seni en iyi ifade eden seçeneği seç.',
        completedMsg: 'Testi tamamladın ve kendin hakkında özel bir şey keşfettin.',
        quizInsights: 'Yolculuğunda ortaya çıkan benzersiz özellikler:',
        goHome: 'Ana Sayfa', loading: 'Yükleniyor...',
    },
    it: {
        ...BASE, name: 'Italiano', flag: '🇮🇹', region: 'International',
        tagline: 'Scopri qualcosa di straordinario su di te', subtitle: 'In soli 60 secondi',
        heroTagline: 'Ogni quiz rivela un aspetto diverso della tua personalità',
        startQuiz: 'Inizia →', chooseOne: 'Scegline uno', chooseOneOrMore: 'Scegline uno o più',
        submitAnswer: 'Invia', submitting: 'Invio...', nextQuestion: 'Successiva →',
        finishQuiz: 'Completa 🎉', completed: 'Incredibile! Ce l\'hai fatta! 🎉',
        yourPersonality: '🌟 Il tuo profilo di personalità',
        tryAnotherQuiz: '🔁 Prova un altro', shareResult: '📤 Condividi',
        question: 'Domanda', of: 'di', seconds: 'secondi',
        takeYourTime: 'Prenditi il tuo tempo. Scegli l\'opzione che ti rappresenta di più.',
        completedMsg: 'Hai completato il quiz e scoperto qualcosa di speciale su di te.',
        quizInsights: 'Tratti unici rivelati nel tuo percorso:',
        goHome: 'Home', loading: 'Caricamento...',
    },
    nl: {
        ...BASE, name: 'Nederlands', flag: '🇳🇱', region: 'International',
        tagline: 'Ontdek iets geweldigs over jezelf', subtitle: 'In slechts 60 seconden',
        heroTagline: 'Elke quiz onthult een ander aspect van je persoonlijkheid',
        startQuiz: 'Starten →', chooseOne: 'Kies er één', chooseOneOrMore: 'Kies er één of meer',
        submitAnswer: 'Verzenden', submitting: 'Verzenden...', nextQuestion: 'Volgende →',
        finishQuiz: 'Afronden 🎉', completed: 'Geweldig! Je hebt het gedaan! 🎉',
        yourPersonality: '🌟 Jouw Persoonlijkheidsrapport',
        tryAnotherQuiz: '🔁 Andere quiz proberen', shareResult: '📤 Delen',
        question: 'Vraag', of: 'van', seconds: 'seconden',
        takeYourTime: 'Neem je tijd. Kies de optie die het meest bij je past.',
        completedMsg: 'Je hebt de quiz voltooid en iets bijzonders over jezelf ontdekt.',
        quizInsights: 'Unieke eigenschappen onthuld tijdens je reis:',
        goHome: 'Home', loading: 'Laden...',
    },
    vi: {
        ...BASE, name: 'Tiếng Việt', flag: '🇻🇳', region: 'International',
        tagline: 'Khám phá điều kỳ diệu về bản thân', subtitle: 'Chỉ trong 60 giây',
        heroTagline: 'Mỗi bài kiểm tra tiết lộ một khía cạnh của tính cách bạn',
        startQuiz: 'Bắt đầu →', chooseOne: 'Chọn một', chooseOneOrMore: 'Chọn một hoặc nhiều',
        submitAnswer: 'Gửi', submitting: 'Đang gửi...', nextQuestion: 'Tiếp theo →',
        finishQuiz: 'Hoàn thành 🎉', completed: 'Tuyệt vời! Bạn đã làm được! 🎉',
        yourPersonality: '🌟 Báo cáo tính cách của bạn',
        tryAnotherQuiz: '🔁 Thử bài khác', shareResult: '📤 Chia sẻ',
        question: 'Câu hỏi', of: '/', seconds: 'giây',
        takeYourTime: 'Hãy từ từ. Chọn câu trả lời phù hợp nhất với bạn.',
        completedMsg: 'Bạn đã hoàn thành bài kiểm tra và khám phá điều đặc biệt về bản thân.',
        quizInsights: 'Những nét tính cách độc đáo được tiết lộ trong hành trình của bạn:',
        goHome: 'Trang chủ', loading: 'Đang tải...',
    },
    th: {
        ...BASE, name: 'ภาษาไทย', flag: '🇹🇭', region: 'International',
        tagline: 'ค้นพบสิ่งที่น่าทึ่งเกี่ยวกับตัวเอง', subtitle: 'ใน 60 วินาที',
        heroTagline: 'แต่ละแบบทดสอบเผยให้เห็นบุคลิกภาพของคุณ',
        startQuiz: 'เริ่ม →', chooseOne: 'เลือกหนึ่งข้อ', chooseOneOrMore: 'เลือกหนึ่งข้อหรือมากกว่า',
        submitAnswer: 'ส่ง', submitting: 'กำลังส่ง...', nextQuestion: 'ถัดไป →',
        finishQuiz: 'เสร็จสิ้น 🎉', completed: 'ยอดเยี่ยม! คุณทำได้! 🎉',
        yourPersonality: '🌟 รายงานบุคลิกภาพ',
        tryAnotherQuiz: '🔁 ลองแบบทดสอบอื่น', shareResult: '📤 แชร์',
        question: 'คำถาม', of: '/', seconds: 'วินาที',
        takeYourTime: 'ใจเย็นๆ เลือกตัวเลือกที่คุณรู้สึกว่าใช่ที่สุด',
        completedMsg: 'คุณทำแบบทดสอบเสร็จแล้วและค้นพบสิ่งพิเศษเกี่ยวกับตัวเอง',
        quizInsights: 'ลักษณะเฉพาะที่ถูกเผยในการเดินทางของคุณ:',
        goHome: 'หน้าหลัก', loading: 'กำลังโหลด...',
    },
    sw: {
        ...BASE, name: 'Kiswahili', flag: '🇰🇪', region: 'International',
        tagline: 'Gundua kitu cha ajabu kuhusu nafsi yako', subtitle: 'Katika sekunde 60 tu',
        heroTagline: 'Kila jaribio linafunua kipengele tofauti cha tabia yako',
        startQuiz: 'Anza →', chooseOne: 'Chagua moja', chooseOneOrMore: 'Chagua moja au zaidi',
        submitAnswer: 'Tuma', submitting: 'Inatuma...', nextQuestion: 'Inayofuata →',
        finishQuiz: 'Maliza 🎉', completed: 'Vizuri sana! Umefanya! 🎉',
        yourPersonality: '🌟 Ripoti ya Tabia Yako',
        tryAnotherQuiz: '🔁 Jaribu Lingine', shareResult: '📤 Shiriki',
        question: 'Swali', of: 'kati ya', seconds: 'sekunde',
        takeYourTime: 'Chukua muda wako. Chagua jibu linalokufanana zaidi.',
        completedMsg: 'Umekamilisha jaribio na kugundua kitu maalum kuhusu nafsi yako.',
        quizInsights: 'Sifa za kipekee zilizogunduliwa katika safari yako:',
        goHome: 'Nyumbani', loading: 'Inapakia...',
    },
    ms: {
        ...BASE, name: 'Melayu', flag: '🇲🇾', region: 'International',
        tagline: 'Temui sesuatu yang menakjubkan tentang diri anda', subtitle: 'Hanya dalam 60 saat',
        heroTagline: 'Setiap kuiz mendedahkan aspek berbeza personaliti anda',
        startQuiz: 'Mula →', chooseOne: 'Pilih satu', chooseOneOrMore: 'Pilih satu atau lebih',
        submitAnswer: 'Hantar', submitting: 'Menghantar...', nextQuestion: 'Seterusnya →',
        finishQuiz: 'Selesai 🎉', completed: 'Hebat! Anda berjaya! 🎉',
        yourPersonality: '🌟 Laporan Personaliti Anda',
        tryAnotherQuiz: '🔁 Cuba Lain', shareResult: '📤 Kongsi',
        question: 'Soalan', of: 'daripada', seconds: 'saat',
        takeYourTime: 'Ambil masa anda. Pilih pilihan yang paling mewakili anda.',
        completedMsg: 'Anda telah menyelesaikan kuiz dan menemui sesuatu yang istimewa tentang diri anda.',
        quizInsights: 'Ciri-ciri unik yang didedahkan sepanjang perjalanan anda:',
        goHome: 'Laman Utama', loading: 'Memuatkan...',
    },
    fa: {
        ...BASE, name: 'فارسی', flag: '🇮🇷', region: 'International',
        tagline: 'چیز شگفت‌انگیزی درباره خودت کشف کن', subtitle: 'تنها در ۶۰ ثانیه',
        heroTagline: 'هر آزمون جنبه‌ای از شخصیت شما را آشکار می‌کند',
        startQuiz: 'شروع →', chooseOne: 'یکی را انتخاب کن', chooseOneOrMore: 'یک یا چند مورد',
        submitAnswer: 'ارسال', submitting: 'در حال ارسال...', nextQuestion: 'بعدی →',
        finishQuiz: 'پایان 🎉', completed: 'عالی! موفق شدی! 🎉',
        yourPersonality: '🌟 گزارش شخصیت شما',
        tryAnotherQuiz: '🔁 آزمون دیگری', shareResult: '📤 اشتراک‌گذاری',
        question: 'سوال', of: 'از', seconds: 'ثانیه',
        takeYourTime: 'عجله نکن. گزینه‌ای را انتخاب کن که بیشترین شباهت را با تو دارد.',
        completedMsg: 'آزمون را تمام کردی و چیز خاصی درباره خودت کشف کردی.',
        quizInsights: 'ویژگی‌های منحصربه‌فرد آشکارشده در مسیرت:',
        goHome: 'صفحه اصلی', loading: 'در حال بارگذاری...',
    },
    pl: {
        ...BASE, name: 'Polski', flag: '🇵🇱', region: 'International',
        tagline: 'Odkryj coś niesamowitego o sobie', subtitle: 'W zaledwie 60 sekund',
        heroTagline: 'Każdy quiz ujawnia inny aspekt Twojej osobowości',
        startQuiz: 'Zacznij →', chooseOne: 'Wybierz jedną', chooseOneOrMore: 'Wybierz jedną lub więcej',
        submitAnswer: 'Prześlij', submitting: 'Wysyłanie...', nextQuestion: 'Następne →',
        finishQuiz: 'Zakończ 🎉', completed: 'Niesamowite! Zrobiłeś to! 🎉',
        yourPersonality: '🌟 Twój Raport Osobowości',
        tryAnotherQuiz: '🔁 Spróbuj innego', shareResult: '📤 Podziel się',
        question: 'Pytanie', of: 'z', seconds: 'sekund',
        takeYourTime: 'Nie śpiesz się. Wybierz opcję, która najlepiej Cię opisuje.',
        completedMsg: 'Ukończyłeś quiz i odkryłeś coś wyjątkowego o sobie.',
        quizInsights: 'Unikalne cechy ujawnione podczas Twojej podróży:',
        goHome: 'Strona główna', loading: 'Ładowanie...',
    },
    uk: {
        ...BASE, name: 'Українська', flag: '🇺🇦', region: 'International',
        tagline: 'Відкрийте щось дивовижне про себе', subtitle: 'Всього за 60 секунд',
        heroTagline: 'Кожна вікторина розкриває новий аспект вашої особистості',
        startQuiz: 'Почати →', chooseOne: 'Оберіть один', chooseOneOrMore: 'Оберіть один або кілька',
        submitAnswer: 'Надіслати', submitting: 'Надсилання...', nextQuestion: 'Наступне →',
        finishQuiz: 'Завершити 🎉', completed: 'Чудово! Ви впорались! 🎉',
        yourPersonality: '🌟 Ваш звіт про особистість',
        tryAnotherQuiz: '🔁 Інша вікторина', shareResult: '📤 Поділитись',
        question: 'Питання', of: 'з', seconds: 'сек',
        takeYourTime: 'Не поспішайте. Виберіть варіант, що найбільше вам підходить.',
        completedMsg: 'Ви пройшли вікторину та відкрили щось особливе в собі.',
        quizInsights: 'Унікальні риси, виявлені у вашій подорожі:',
        goHome: 'На головну', loading: 'Завантаження...',
    },
    el: {
        ...BASE, name: 'Ελληνικά', flag: '🇬🇷', region: 'International',
        tagline: 'Ανακαλύψτε κάτι εκπληκτικό για τον εαυτό σας', subtitle: 'Μόλις σε 60 δευτερόλεπτα',
        heroTagline: 'Κάθε κουίζ αποκαλύπτει μια διαφορετική πτυχή της προσωπικότητάς σας',
        startQuiz: 'Έναρξη →', chooseOne: 'Επιλέξτε ένα', chooseOneOrMore: 'Επιλέξτε ένα ή περισσότερα',
        submitAnswer: 'Υποβολή', submitting: 'Υποβάλλεται...', nextQuestion: 'Επόμενο →',
        finishQuiz: 'Ολοκλήρωση 🎉', completed: 'Φανταστικό! Τα κατάφερες! 🎉',
        yourPersonality: '🌟 Η αναφορά προσωπικότητάς σου',
        tryAnotherQuiz: '🔁 Δοκίμασε άλλο', shareResult: '📤 Κοινοποίηση',
        question: 'Ερώτηση', of: 'από', seconds: 'δευτερόλεπτα',
        takeYourTime: 'Πάρε τον χρόνο σου. Διάλεξε αυτό που σε αντιπροσωπεύει περισσότερο.',
        completedMsg: 'Ολοκλήρωσες το κουίζ και ανακάλυψες κάτι ιδιαίτερο για σένα.',
        quizInsights: 'Μοναδικά χαρακτηριστικά που αποκαλύφθηκαν στο ταξίδι σου:',
        goHome: 'Αρχική', loading: 'Φόρτωση...',
    },
    cs: {
        ...BASE, name: 'Čeština', flag: '🇨🇿', region: 'International',
        tagline: 'Objevte něco úžasného o sobě', subtitle: 'Za pouhých 60 sekund',
        heroTagline: 'Každý kvíz odhaluje jiný aspekt vaší osobnosti',
        startQuiz: 'Začít →', chooseOne: 'Vyberte jednu', chooseOneOrMore: 'Vyberte jednu nebo více',
        submitAnswer: 'Odeslat', submitting: 'Odesílání...', nextQuestion: 'Další →',
        finishQuiz: 'Dokončit 🎉', completed: 'Úžasné! Dokázal jsi to! 🎉',
        yourPersonality: '🌟 Váš osobnostní profil',
        tryAnotherQuiz: '🔁 Zkusit jiný', shareResult: '📤 Sdílet',
        question: 'Otázka', of: 'z', seconds: 'sekund',
        takeYourTime: 'Ber si čas. Vyber možnost, která tě nejlépe vystihuje.',
        completedMsg: 'Dokončil jsi kvíz a chobil jsi něco zvláštního o sobě.',
        quizInsights: 'Jedinečné vlastnosti odhalené na tvé cestě:',
        goHome: 'Domů', loading: 'Načítání...',
    },
    ro: {
        ...BASE, name: 'Română', flag: '🇷🇴', region: 'International',
        tagline: 'Descoperă ceva uimitor despre tine', subtitle: 'În doar 60 de secunde',
        heroTagline: 'Fiecare chestionar dezvăluie un aspect diferit al personalității tale',
        startQuiz: 'Începe →', chooseOne: 'Alege una', chooseOneOrMore: 'Alege una sau mai multe',
        submitAnswer: 'Trimite', submitting: 'Se trimite...', nextQuestion: 'Următoarea →',
        finishQuiz: 'Finalizează 🎉', completed: 'Incredibil! Ai reușit! 🎉',
        yourPersonality: '🌟 Raportul tău de personalitate',
        tryAnotherQuiz: '🔁 Încearcă altul', shareResult: '📤 Distribuie',
        question: 'Întrebare', of: 'din', seconds: 'secunde',
        takeYourTime: 'Ia-ți timp. Alege opțiunea care te reprezintă cel mai bine.',
        completedMsg: 'Ai finalizat chestionarul și ai descoperit ceva special despre tine.',
        quizInsights: 'Trăsături unice dezvăluite pe parcursul călătoriei tale:',
        goHome: 'Acasă', loading: 'Se încarcă...',
    },
    hu: {
        ...BASE, name: 'Magyar', flag: '🇭🇺', region: 'International',
        tagline: 'Fedezz fel valamit csodálatosat magadban', subtitle: 'Mindössze 60 másodperc alatt',
        heroTagline: 'Minden kvíz személyiséged egy más aspektusát tárja fel',
        startQuiz: 'Kezdés →', chooseOne: 'Válassz egyet', chooseOneOrMore: 'Válassz egyet vagy többet',
        submitAnswer: 'Beküldés', submitting: 'Küldés...', nextQuestion: 'Következő →',
        finishQuiz: 'Befejezés 🎉', completed: 'Fantasztikus! Sikerült! 🎉',
        yourPersonality: '🌟 Személyiség-jelentésed',
        tryAnotherQuiz: '🔁 Próbálj másikat', shareResult: '📤 Megosztás',
        question: 'Kérdés', of: '/', seconds: 'másodperc',
        takeYourTime: 'Ne siettesd magad. Válaszd azt, ami a legjobban illik rád.',
        completedMsg: 'Befejezted a kvízt és fedeztél fel valami különlegeset magadban.',
        quizInsights: 'Az utadon feltárt egyedi tulajdonságok:',
        goHome: 'Kezdőlap', loading: 'Betöltés...',
    },
    sv: {
        ...BASE, name: 'Svenska', flag: '🇸🇪', region: 'International',
        tagline: 'Upptäck något fantastiskt om dig själv', subtitle: 'På bara 60 sekunder',
        heroTagline: 'Varje quiz avslöjar en annan aspekt av din personlighet',
        startQuiz: 'Börja →', chooseOne: 'Välj ett', chooseOneOrMore: 'Välj ett eller flera',
        submitAnswer: 'Skicka', submitting: 'Skickar...', nextQuestion: 'Nästa →',
        finishQuiz: 'Avsluta 🎉', completed: 'Fantastiskt! Du klarade det! 🎉',
        yourPersonality: '🌟 Din personlighetsrapport',
        tryAnotherQuiz: '🔁 Prova ett annat', shareResult: '📤 Dela',
        question: 'Fråga', of: 'av', seconds: 'sekunder',
        takeYourTime: 'Ta din tid. Välj alternativet som stämmer bäst in på dig.',
        completedMsg: 'Du avslutade quizet och upptäckte något speciellt om dig själv.',
        quizInsights: 'Unika egenskaper som avslöjades under din resa:',
        goHome: 'Hem', loading: 'Laddar...',
    },
    no: {
        ...BASE, name: 'Norsk', flag: '🇳🇴', region: 'International',
        tagline: 'Oppdag noe fantastisk om deg selv', subtitle: 'På bare 60 sekunder',
        heroTagline: 'Hver quiz avslører en annen side av din personlighet',
        startQuiz: 'Start →', chooseOne: 'Velg en', chooseOneOrMore: 'Velg en eller flere',
        submitAnswer: 'Send', submitting: 'Sender...', nextQuestion: 'Neste →',
        finishQuiz: 'Avslutt 🎉', completed: 'Fantastisk! Du klarte det! 🎉',
        yourPersonality: '🌟 Din personlighetsrapport',
        tryAnotherQuiz: '🔁 Prøv en annen', shareResult: '📤 Del',
        question: 'Spørsmål', of: 'av', seconds: 'sekunder',
        takeYourTime: 'Ta deg god tid. Velg alternativet som passer best til deg.',
        completedMsg: 'Du fullførte quizen og oppdaget noe spesielt om deg selv.',
        quizInsights: 'Unike egenskaper avdekket på reisen din:',
        goHome: 'Hjem', loading: 'Laster...',
    },

    // ── INDIAN LANGUAGES ───────────────────────────────────────────
    bho: {
        ...BASE, name: 'भोजपुरी', flag: '🪔', region: 'Indian',
        tagline: 'अपने बारे में कुछ अनोखा जानीं', subtitle: 'बस 60 सेकंड में',
        heroTagline: 'हर क्विज़ रउआ के व्यक्तित्व के एगो अलग पहलू बतावेला',
        startQuiz: 'क्विज़ शुरू करीं →', chooseOne: 'एगो चुनीं', chooseOneOrMore: 'एगो या अधिक चुनीं',
        submitAnswer: 'जवाब जमा करीं', submitting: 'जमा हो रहल बा...', nextQuestion: 'अगिला सवाल →',
        finishQuiz: 'क्विज़ खतम करीं 🎉', completed: 'जबरदस्त! रउआ कर देखलीं! 🎉',
        yourPersonality: '🌟 रउआ के व्यक्तित्व रिपोर्ट',
        tryAnotherQuiz: '🔁 दूसर क्विज़ आज़माईं', shareResult: '📤 नतीजा शेयर करीं',
        tryAgain: 'फेर कोशिश करीं', question: 'सवाल', of: 'में से', seconds: 'सेकंड',
        takeYourTime: 'समय लीं। ऊ विकल्प चुनीं जे सबसे जादा लागे।',
        completedMsg: 'रउआ क्विज़ पूरा कर देखलीं आ अपने बारे में कुछ खास जानलीं!',
        quizInsights: 'रउआ के यात्रा में उजागर भइल अनूठी खूबियाँ:',
        goHome: 'होम पर जाईं', loading: 'लोड हो रहल बा...',
    },
    mai: {
        ...BASE, name: 'मैथिली', flag: '📖', region: 'Indian',
        tagline: 'अपना बारे में किछु अद्भुत जानू', subtitle: 'मात्र 60 सेकेंड में',
        heroTagline: 'प्रत्येक क्विज़ अहाँक व्यक्तित्वक एकटा अलग पक्ष प्रकट करैत अछि',
        startQuiz: 'क्विज़ शुरू करू →', chooseOne: 'एकटा चुनू', chooseOneOrMore: 'एकटा वा अधिक चुनू',
        submitAnswer: 'उत्तर जमा करू', submitting: 'जमा भऽ रहल अछि...', nextQuestion: 'अगिला प्रश्न →',
        finishQuiz: 'क्विज़ समाप्त करू 🎉', completed: 'शानदार! अहाँ कऽ देखेलहुँ! 🎉',
        yourPersonality: '🌟 अहाँक व्यक्तित्व रिपोर्ट',
        tryAnotherQuiz: '🔁 दोसर क्विज़ आज़माऊ', shareResult: '📤 परिणाम साझा करू',
        tryAgain: 'पुनः प्रयास करू', question: 'प्रश्न', of: 'में', seconds: 'सेकेंड',
        takeYourTime: 'समय लियऽ। सभसँ उचित विकल्प चुनू।',
        completedMsg: 'अहाँ क्विज़ पूरा केलहुँ आ अपना बारे में किछु विशेष जानलहुँ!',
        quizInsights: 'अहाँक यात्रामें प्रकट भेल अनन्य विशेषताएँ:',
        goHome: 'होम पर जाउ', loading: 'लोड भऽ रहल अछि...',
    },
    mr: {
        ...BASE, name: 'मराठी', flag: '🟧', region: 'Indian',
        tagline: 'स्वतःबद्दल काहीतरी अप्रतिम शोधा', subtitle: 'केवळ 60 सेकंदात',
        heroTagline: 'प्रत्येक प्रश्नमंजुषा तुमच्या व्यक्तिमत्त्वाचा वेगळा पैलू उघड करते',
        startQuiz: 'सुरू करा →', chooseOne: 'एक निवडा', chooseOneOrMore: 'एक किंवा अधिक निवडा',
        submitAnswer: 'सादर करा', submitting: 'सादर होत आहे...', nextQuestion: 'पुढील प्रश्न →',
        finishQuiz: 'संपवा 🎉', completed: 'अप्रतिम! तुम्ही केलेत! 🎉',
        yourPersonality: '🌟 तुमचा व्यक्तिमत्त्व अहवाल',
        tryAnotherQuiz: '🔁 दुसरी कुइज', shareResult: '📤 शेअर करा',
        tryAgain: 'पुन्हा प्रयत्न करा', question: 'प्रश्न', of: 'पैकी', seconds: 'सेकंद',
        takeYourTime: 'वेळ घ्या. जे तुम्हाला सर्वात जास्त वाटते ते निवडा.',
        completedMsg: 'तुम्ही क्विज पूर्ण केली आणि स्वतःबद्दल काहीतरी विशेष शोधलं!',
        quizInsights: 'तुमच्या प्रवासात उघड झालेल्या अनन्य गुणविशेष:',
        goHome: 'मुख्यपृष्ठ', loading: 'लोड होत आहे...',
    },
    gu: {
        ...BASE, name: 'ગુજરાતી', flag: '🦋', region: 'Indian',
        tagline: 'તમારા વિશે કંઈક અદ્ભુત શોધો', subtitle: 'ફક્ત 60 સેકન્ડમાં',
        heroTagline: 'દરેક ક્વિઝ તમારા વ્યક્તિત્વના અલગ પાસાને ઉજાગર કરે છે',
        startQuiz: 'ક્વિઝ શરૂ →', chooseOne: 'એક પસંદ કરો', chooseOneOrMore: 'એક અથવા વધુ પસંદ કરો',
        submitAnswer: 'જવાબ સ્વીકારો', submitting: 'સ્વીકારી રહ્યા...', nextQuestion: 'આગળ →',
        finishQuiz: 'ક્વિઝ પૂર્ણ 🎉', completed: 'અદ્ભુત! તમે કરી બતાવ્યું! 🎉',
        yourPersonality: '🌟 તમારો વ્યક્તિત્વ અહેવાલ',
        tryAnotherQuiz: '🔁 બીજી ક્વિઝ', shareResult: '📤 શેર કરો',
        tryAgain: 'ફરી પ્રયાસ કરો', question: 'સવાલ', of: 'માં', seconds: 'સેકન્ડ',
        takeYourTime: 'સમય લો. જે વિકલ્પ તમને સૌથી સારો લાગે તે પસંદ કરો.',
        completedMsg: 'તમે ક્વિઝ પૂર્ણ કરી અને તમારા વિશે કંઈ ખાસ શોધ્યું!',
        quizInsights: 'તમારી યાત્રામાં ઉજાગર થયેલ અનન્ય ગુણો:',
        goHome: 'હોમ', loading: 'લોડ થઈ રહ્યું છે...',
    },
    raj: {
        ...BASE, name: 'राजस्थानी', flag: '🏰', region: 'Indian',
        tagline: 'आपणे बारे में कोई अनोखी चीज जाणो', subtitle: 'बस 60 सेकंड में',
        heroTagline: 'हर क्विज़ आपकी शख्सियत रो एक अलग पहलू सामने लावे',
        startQuiz: 'क्विज़ शुरू करो →', chooseOne: 'एक चुणो', chooseOneOrMore: 'एक या ज्यादा चुणो',
        submitAnswer: 'जवाब जमा करो', submitting: 'जमा हो रह्यो...', nextQuestion: 'अगलो सवाल →',
        finishQuiz: 'क्विज़ खतम 🎉', completed: 'जबरदस्त! तमने कर दिखायो! 🎉',
        yourPersonality: '🌟 आपकी शख्सियत रिपोर्ट',
        tryAnotherQuiz: '🔁 दूसरी क्विज़', shareResult: '📤 नतीजा शेयर करो',
        tryAgain: 'फेर कोशिश करो', question: 'सवाल', of: 'में', seconds: 'सेकंड',
        takeYourTime: 'समय लो। ऊ विकल्प चुणो जाको सबसे ज्यादा लागे।',
        completedMsg: 'आपणे क्विज़ पूरो कर दिखायो आर आपणे बारे में कुछ खास जाण्यो!',
        quizInsights: 'आपकी यात्रा में उजागर भई अनोखी खूबियाँ:',
        goHome: 'होम पर जावो', loading: 'लोड हो रह्यो...',
    },
    pa: {
        ...BASE, name: 'ਪੰਜਾਬੀ', flag: '🌾', region: 'Indian',
        tagline: 'ਆਪਣੇ ਬਾਰੇ ਕੁਝ ਅਦਭੁਤ ਲੱਭੋ', subtitle: 'ਸਿਰਫ਼ 60 ਸਕਿੰਟਾਂ ਵਿੱਚ',
        heroTagline: 'ਹਰ ਕੁਇਜ਼ ਤੁਹਾਡੀ ਸ਼ਖ਼ਸੀਅਤ ਦਾ ਵੱਖਰਾ ਪਹਿਲੂ ਦੱਸਦਾ ਹੈ',
        startQuiz: 'ਸ਼ੁਰੂ ਕਰੋ →', chooseOne: 'ਇੱਕ ਚੁਣੋ', chooseOneOrMore: 'ਇੱਕ ਜਾਂ ਵੱਧ ਚੁਣੋ',
        submitAnswer: 'ਜਮ੍ਹਾਂ ਕਰੋ', submitting: 'ਜਮ੍ਹਾਂ ਹੋ ਰਿਹਾ...', nextQuestion: 'ਅਗਲਾ →',
        finishQuiz: 'ਖਤਮ 🎉', completed: 'ਸ਼ਾਨਦਾਰ! ਤੁਸੀਂ ਕਰ ਦਿਖਾਇਆ! 🎉',
        yourPersonality: '🌟 ਤੁਹਾਡੀ ਸ਼ਖ਼ਸੀਅਤ ਰਿਪੋਰਟ',
        tryAnotherQuiz: '🔁 ਹੋਰ ਕੁਇਜ਼', shareResult: '📤 ਸਾਂਝਾ ਕਰੋ',
        tryAgain: 'ਮੁੜ ਕੋਸ਼ਿਸ਼ ਕਰੋ2', question: 'ਸਵਾਲ', of: 'ਵਿੱਚੋਂ', seconds: 'ਸਕਿੰਟ',
        takeYourTime: 'ਸਮਾਂ ਲਓ। ਉਹ ਵਿਕਲਪ ਚੁਣੋ ਜੋ ਤੁਹਾਨੂੰ ਸਭ ਤੋਂ ਵੱਧ ਲੱਗਦਾ ਹੈ।',
        completedMsg: 'ਤੁਸੀਂ ਕੁਇਜ਼ ਪੂਰੀ ਕੀਤੀ ਅਤੇ ਆਪਣੇ ਬਾਰੇ ਕੁਝ ਖਾਸ ਜਾਣਿਆ!',
        quizInsights: 'ਤੁਹਾਡੀ ਯਾਤਰਾ ਵਿੱਚ ਸਾਹਮਣੇ ਆਈਆਂ ਵਿਲੱਖਣ ਖੂਬੀਆਂ:',
        goHome: 'ਮੁੱਖ ਪੰਨਾ', loading: 'ਲੋਡ ਹੋ ਰਿਹਾ...',
    },
    ml: {
        ...BASE, name: 'മലയാളം', flag: '🌴', region: 'Indian',
        tagline: 'നിങ്ങളെ കുറിച്ച് അത്ഭുതകരമായ കാര്യങ്ങൾ കണ്ടെത്തൂ', subtitle: 'വെറും 60 സെക്കൻഡിൽ',
        heroTagline: 'ഓരോ ക്വിസ്സും നിങ്ങളുടെ വ്യക്തിത്വത്തിന്റെ ഒരു വ്യത്യസ്ത വശം വെളിപ്പെടുത്തുന്നു',
        startQuiz: 'ആരംഭിക്കൂ →', chooseOne: 'ഒന്ന് തിരഞ്ഞെടുക്കൂ', chooseOneOrMore: 'ഒന്നോ അതിലധികമോ',
        submitAnswer: 'സമർപ്പിക്കൂ', submitting: 'സമർപ്പിക്കുന്നു...', nextQuestion: 'അടുത്ത ചോദ്യം →',
        finishQuiz: 'പൂർത്തിയാക്കൂ 🎉', completed: 'അതിശയം! നിങ്ങൾ ചെയ്തു! 🎉',
        yourPersonality: '🌟 നിങ്ങളുടെ വ്യക്തിത്വ റിപ്പോർട്ട്',
        tryAnotherQuiz: '🔁 മറ്റൊരു ക്വിസ്', shareResult: '📤 പങ്കിടൂ',
        tryAgain: 'വീണ്ടും ശ്രമിക്കൂ', question: 'ചോദ്യം', of: 'ൽ', seconds: 'സെക്കൻഡ്',
        takeYourTime: 'സമയം എടുക്കൂ. ആദ്യം തോന്നുന്ന ഉത്തരം തിരഞ്ഞെടുക്കൂ.',
        completedMsg: 'നിങ്ങൾ ക്വിസ്സ് പൂർത്തിയാക്കുകയും നിങ്ങളെ കുറിച്ച് വിശേഷകരമായ കാര്യം കണ്ടെത്തുകയും ചെയ്തു!',
        quizInsights: 'നിങ്ങളുടെ യാത്രയിൽ വെളിപ്പെട്ട അതുല്യ സ്വഭാവ ഗുണങ്ങൾ:',
        goHome: 'ഹോം', loading: 'ലോഡ് ചെയ്യുന്നു...',
    },
    or: {
        ...BASE, name: 'ଓଡ଼ିଆ', flag: '🏵️', region: 'Indian',
        tagline: 'ନିଜ ବିଷୟରେ କିଛି ଅଦ୍ଭୁତ ଆବିଷ୍କାର କରନ୍ତୁ', subtitle: 'ମାତ୍ର ୬୦ ସେକେଣ୍ଡ‌ରେ',
        heroTagline: 'ପ୍ରତ୍ୟେକ କ୍ୱିଜ ଆପଣଙ୍କ ବ୍ୟକ୍ତିତ୍ୱର ଏକ ଭିନ୍ନ ଦିଗ ପ୍ରକାଶ କରେ',
        startQuiz: 'ଆରମ୍ଭ →', chooseOne: 'ଗୋଟିଏ ବଛନ୍ତୁ', chooseOneOrMore: 'ଗୋଟିଏ ବା ଅଧିକ',
        submitAnswer: 'ଦିଅନ୍ତୁ', submitting: 'ଦେଉଛି...', nextQuestion: 'ପରବର୍ତ୍ତୀ →',
        finishQuiz: 'ସମ୍ପୂର୍ଣ୍ଣ 🎉', completed: 'ଅଦ୍ଭୁତ! ଆପଣ ଏହା କଲେ! 🎉',
        yourPersonality: '🌟 ଆପଣଙ୍କ ବ୍ୟକ୍ତିତ୍ୱ ରିପୋର୍ଟ',
        tryAnotherQuiz: '🔁 ଅନ୍ୟ କ୍ୱିଜ', shareResult: '📤 ଭାଗ କରନ୍ତୁ',
        tryAgain: 'ପୁଣି ଚେଷ୍ଟା', question: 'ପ୍ରଶ୍ନ', of: 'ରୁ', seconds: 'ସେକେଣ୍ଡ',
        takeYourTime: 'ସମୟ ନିଅନ୍ତୁ। ଯେଉଁ ଉତ୍ତର ଠିକ ଲାଗୁଛି ଚୟନ କରନ୍ତୁ।',
        completedMsg: 'ଆପଣ କ୍ୱିଜ ସମ୍ପୂର୍ଣ୍ଣ କଲେ ଏବଂ ନିଜ ବିଷୟରେ ଏକ ବିଶେଷ ଜିନିଷ ଆବିଷ୍କାର କଲେ!',
        quizInsights: 'ଆପଣଙ୍କ ଯାତ୍ରାରେ ପ୍ରକାଶ ପାଇଥିବା ଅନନ୍ୟ ଗୁଣ:',
        goHome: 'ହୋମ', loading: 'ଲୋଡ ହେଉଛି...',
    },
    as: {
        ...BASE, name: 'অসমীয়া', flag: '🌿', region: 'Indian',
        tagline: 'নিজৰ বিষয়ে কিবা আচৰিত কথা আৱিষ্কাৰ কৰক', subtitle: 'মাত্ৰ ৬০ ছেকেণ্ডতে',
        heroTagline: 'প্ৰতিটো কুইজে আপোনাৰ ব্যক্তিত্বৰ এটা বেলেগ দিশ উন্মোচন কৰে',
        startQuiz: 'আৰম্ভ কৰক →', chooseOne: 'এটা বাছক', chooseOneOrMore: 'এটা বা অধিক বাছক',
        submitAnswer: 'দাখিল কৰক', submitting: 'দাখিল হৈছে...', nextQuestion: 'পৰৱৰ্তী →',
        finishQuiz: 'শেষ কৰক 🎉', completed: 'অসাধাৰণ! আপুনি কৰিলে! 🎉',
        yourPersonality: '🌟 আপোনাৰ ব্যক্তিত্ব প্ৰতিবেদন',
        tryAnotherQuiz: '🔁 আন কুইজ', shareResult: '📤 ভাগ কৰক',
        tryAgain: 'পুনৰ চেষ্টা', question: 'প্ৰশ্ন', of: 'ৰ', seconds: 'ছেকেণ্ড',
        takeYourTime: 'সময় লওক। যি বিকল্পটো আটাইতকৈ উপযুক্ত লাগে সেইটো বাছক।',
        completedMsg: 'আপুনি কুইজটো সম্পূৰ্ণ কৰিলে আৰু নিজৰ বিষয়ে বিশেষ কিবা আৱিষ্কাৰ কৰিলে!',
        quizInsights: 'আপোনাৰ যাত্ৰাত প্ৰকাশ পোৱা অনন্য বৈশিষ্ট্যসমূহ:',
        goHome: 'হোম', loading: 'লোড হৈছে...',
    },
    bn: {
        ...BASE, name: 'বাংলা', flag: '🌸', region: 'Indian',
        tagline: 'নিজের সম্পর্কে অবিশ্বাস্য কিছু আবিষ্কার করুন', subtitle: 'মাত্র ৬০ সেকেন্ডে',
        heroTagline: 'প্রতিটি কুইজ আপনার ব্যক্তিত্বের একটি আলাদা দিক প্রকাশ করে',
        startQuiz: 'শুরু করুন →', chooseOne: 'একটি বেছে নিন', chooseOneOrMore: 'একটি বা বেশি বেছে নিন',
        submitAnswer: 'জমা দিন', submitting: 'জমা হচ্ছে...', nextQuestion: 'পরের প্রশ্ন →',
        finishQuiz: 'শেষ করুন 🎉', completed: 'দারুণ! আপনি করে দেখিয়েছেন! 🎉',
        yourPersonality: '🌟 আপনার ব্যক্তিত্ব রিপোর্ট',
        tryAnotherQuiz: '🔁 আরেকটি কুইজ', shareResult: '📤 শেয়ার করুন',
        tryAgain: 'আবার চেষ্টা', question: 'প্রশ্ন', of: 'এর', seconds: 'সেকেন্ড',
        takeYourTime: 'সময় নিন। যে বিকল্পটি সবচেয়ে মানানসই মনে হয় সেটি বেছে নিন।',
        completedMsg: 'আপনি কুইজ সম্পন্ন করেছেন এবং নিজের সম্পর্কে বিশেষ কিছু জেনেছেন!',
        quizInsights: 'আপনার যাত্রায় প্রকাশিত অনন্য বৈশিষ্ট্যসমূহ:',
        goHome: 'হোম', loading: 'লোড হচ্ছে...',
    },
    ur: {
        ...BASE, name: 'اردو', flag: '📜', region: 'Indian',
        tagline: 'اپنے بارے میں کچھ حیرت انگیز دریافت کریں', subtitle: 'صرف 60 سیکنڈ میں',
        heroTagline: 'ہر کوئز آپ کی شخصیت کا ایک مختلف پہلو ظاہر کرتا ہے',
        startQuiz: 'شروع کریں →', chooseOne: 'ایک منتخب کریں', chooseOneOrMore: 'ایک یا زیادہ منتخب کریں',
        submitAnswer: 'جمع کریں', submitting: 'جمع ہو رہا ہے...', nextQuestion: 'اگلا سوال →',
        finishQuiz: 'ختم کریں 🎉', completed: 'شاندار! آپ نے کر دکھایا! 🎉',
        yourPersonality: '🌟 آپ کی شخصیت رپورٹ',
        tryAnotherQuiz: '🔁 دوسری کوئز', shareResult: '📤 شیئر کریں',
        tryAgain: 'دوبارہ کوشش', wrongPassword: 'غلط پاسورڈ۔', question: 'سوال', of: 'میں سے', seconds: 'سیکنڈ',
        takeYourTime: 'وقت لیں۔ وہ آپشن چنیں جو آپ کو سب سے مناسب لگے۔',
        completedMsg: 'آپ نے کوئز مکمل کیا اور اپنے بارے میں کچھ خاص جانا!',
        quizInsights: 'آپ کے سفر میں کشف ہونے والی منفرد خصوصیات:',
        goHome: 'ہوم', loading: 'لوڈ ہو رہا ہے...',
    },
    ne: {
        ...BASE, name: 'नेपाली', flag: '🏔️', region: 'Indian',
        tagline: 'आफ्नो बारेमा केही अद्भुत पत्ता लगाउनुहोस्', subtitle: 'केवल ६० सेकेन्डमा',
        heroTagline: 'प्रत्येक क्विजले तपाईंको व्यक्तित्वको फरक पक्ष उजागर गर्छ',
        startQuiz: 'सुरू →', chooseOne: 'एउटा छान्नुहोस्', chooseOneOrMore: 'एउटा वा बढी छान्नुहोस्',
        submitAnswer: 'पठाउनुहोस्', submitting: 'पठाइँदैछ...', nextQuestion: 'अर्को →',
        finishQuiz: 'सकाउनुहोस् 🎉', completed: 'अद्भुत! तपाईंले गर्नुभयो! 🎉',
        yourPersonality: '🌟 तपाईंको व्यक्तित्व रिपोर्ट',
        tryAnotherQuiz: '🔁 अर्को क्विज', shareResult: '📤 साझा गर्नुहोस्',
        tryAgain: 'पुनः प्रयास', question: 'प्रश्न', of: 'मध्ये', seconds: 'सेकेन्ड',
        takeYourTime: 'समय लिनुहोस्। सबैभन्दा उपयुक्त विकल्प छान्नुहोस्।',
        completedMsg: 'तपाईंले क्विज पूरा गर्नुभयो र आफ्नो बारेमा केही विशेष पत्ता लगाउनुभयो!',
        quizInsights: 'तपाईंको यात्रामा उजागर भएका अनन्य विशेषताहरू:',
        goHome: 'गृहपृष्ठ', loading: 'लोड हुँदैछ...',
    },
    sa: {
        ...BASE, name: 'संस्कृतम्', flag: '🕉️', region: 'Indian',
        tagline: 'स्वयं विषये किमपि आश्चर्यकरं जानीत', subtitle: 'केवलं षष्टिषु सेकण्डेषु',
        heroTagline: 'प्रतिश्रेणिः आपणस्य व्यक्तित्वस्य भिन्नं पक्षं प्रकटयति',
        startQuiz: 'आरभत →', chooseOne: 'एकं चिनुत', chooseOneOrMore: 'एकं वा अधिकं चिनुत',
        submitAnswer: 'प्रेषयत', submitting: 'प्रेष्यते...', nextQuestion: 'अग्रिमः →',
        finishQuiz: 'समाप्यताम् 🎉', completed: 'अद्भुतम्! भवान् कृतवान्! 🎉',
        yourPersonality: '🌟 भवतः व्यक्तित्वप्रतिवेदनम्',
        tryAnotherQuiz: '🔁 अन्यां प्रश्नोत्तरीं', shareResult: '📤 साझयत',
        tryAgain: 'पुनः प्रयत्नत', question: 'प्रश्नः', of: 'तः', seconds: 'सेकण्डाः',
        takeYourTime: 'समयः गृह्यताम्। यः विकल्पः उचितः मन्यते सः चीयताम्।',
        completedMsg: 'भवान् प्रश्नोत्तरीं पूर्णां कृतवान् आत्मविषये किमपि विशेषं जानाति!',
        quizInsights: 'भवतः यात्रायां प्रकटिताः अनन्याः विशेषताः:',
        goHome: 'मुखपृष्ठम्', loading: 'लोडनं भवति...',
    },
    sd: {
        ...BASE, name: 'سنڌي', flag: '🏺', region: 'Indian',
        tagline: 'پنهنجي باري ۾ ڪجهه حيرت انگيز دريافت ڪريو', subtitle: 'صرف 60 سيڪنڊن ۾',
        heroTagline: 'هر ڪوئز توهان جي شخصيت جو هڪ مختلف پهلو ظاهر ڪري ٿو',
        startQuiz: 'شروع ڪريو →', chooseOne: 'هڪ چونڊيو', chooseOneOrMore: 'هڪ يا وڌيڪ',
        submitAnswer: 'جمع ڪريو', submitting: 'جمع ٿي رهيو...',  nextQuestion: 'ايندڙ →',
        finishQuiz: 'ختم ڪريو 🎉', completed: 'شاندار! آپ ڪري ڏيکاريو! 🎉',
        yourPersonality: '🌟 توهان جي شخصيت رپورٽ',
        tryAnotherQuiz: '🔁 ٻيو ڪوئز', shareResult: '📤 شيئر ڪريو',
        tryAgain: 'ٻيهر ڪوشش ڪريو', question: 'سوال', of: 'مان', seconds: 'سيڪنڊ',
        takeYourTime: 'وقت وٺو. اهو آپشن چونڊيو جيڪو توهان کي وڌيڪ مناسب لڳي.',
        completedMsg: 'توهان ڪوئز مڪمل ڪيو ۽ پنهنجي باري ۾ ڪجهه خاص ڄاڻيو!',
        quizInsights: 'توهان جي سفر ۾ ظاهر ٿيل منفرد خصوصيتون:',
        goHome: 'هوم', loading: 'لوڊ ٿي رهيو...',
    },
};

// ── Language groups for the compact globe picker ──────────────────
export const LANGUAGE_GROUPS = [
    {
        label: 'International 🌍',
        langs: ['en','es','fr','ar','zh','pt','de','ja','ko','ru','id','tr','it','nl','vi','th','sw','ms','fa','pl','uk','el','cs','ro','hu','sv','no'],
    },
    {
        label: 'भारतीय 🇮🇳',
        langs: ['hi','bho','mai','mr','gu','raj','pa','te','ta','kn','ml','or','as','bn','ur','ne','sa','sd'],
    },
];

export const LanguageContext = createContext();

export const LanguageProvider = ({ children }) => {
    const [language, setLanguage] = useState('en');
    const t = translations[language] || translations.en;
    return (
        <LanguageContext.Provider value={{ language, setLanguage, t, translations, LANGUAGE_GROUPS }}>
            {children}
        </LanguageContext.Provider>
    );
};

export const useLanguage = () => useContext(LanguageContext);
